---
title: "NCF_Careers_Sankey"
author: "Marina Sanchez"
date: "1/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### SANKEY DIAGRAM ###
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(highcharter)

mypath <- "D:/Datos/Documents/Development/R/Data Visualization/Datasets/NCAlumn.csv"
alumn <- read.csv(file=mypath, na.strings=c("", "NA"))
dim(alumn)
summary(alumn)
colnames(alumn)
head(alumn)

div1_ind <- alumn %>% select(DIVISION_1, Industry) %>%
  filter(! is.na(DIVISION_1)) %>%
  filter(! is.na(Industry)) %>%
  mutate(Industry=as.character(Industry)) %>%
  mutate(Industry = fct_collapse(Industry,
    Entertaintment = c("Arts","Media", "Music","Entertainment", "Journalism",
                       "Publishing", "Archaeology", "Arts & Entertainment",
                       "Film", "Performing Arts", "Architecture", "Communications",
                       "Antiques", "Hospitality", "Online Media", "Advertising",
                       "Art", "Religion", "Photography", "Library", "Museums and Institutions"),
    Health = c("Healthcare", "Medical", "Health & Fitness", "Healthcare Services",
               "Medicine", "Psychotherapy", "Public Health", "Dentistry",
               "Medical Research","Pharmaceutical", "Imaging"),
    STEM = c("Software", "Technology", "Engineering","Information Technology","Research",
             "Environmental", "Data Science", "Environmental Services", "IT Communications", 
             "Construction", "Environmental Science", "Software Design", "Computer Software",
             "Electronics", "Home Improvement"),
    Education = c("Education", "Educational Services", "Higher education", "Development", "Education / Training"),
    Finances = c("Marketing", "Retail", "Financial Services", "Food", "Food Franchise",
                         "Food Service", "Food and Lodging", "Restaurant", "Banking","Business Consulting",
                         "Real Estate", "Business", "Consulting", "Insurance",
                         "Manufacturing", "Health Care Consulting", "Human Resources",
                         "International Economic Development Consulting", "Public Relations",
                         "Accounting", "Investment banking", "Investments",
                         "Non-profit consulting", "Medical Equipment", "Pet Food", 
                         "Shipping", "Sports Management", "Textiles",
                         "Transportation", "Agriculture", "Farming"),
    Government = c("Law", "Military", "Environmental Law","Attorney",
                   "Non Profit", "Nonprofit", "Government", "City/County/State",
                   "Community Services","Services", "Defense & Space","Economic Development",
                   "International Relations", "Marine","Philanthropy")
  )) %>%
  mutate(DIVISION_1=as.character(DIVISION_1))

#Final dataframe
names(div1_ind) <- c('College Major', 'Proffesional Career') #Rename columns
#div1_ind

#Fake testing data
#division <- c("Humanities", "Interdisciplinary", "Natural Science", "Social Science")
#industry <- c('Finance Business', 'Entertainment', 'Government', 'STEM', 'Health', 'Education')
# t1 <- sample(x = division , size = 100, replace=TRUE)
# #t2 <- sample(x = c("Male", "Female")   , size = 100, replace=TRUE)
# t2 <- sample(x = industry , size = 100, replace=TRUE)
# d <- data.frame(cbind(t1,t2))
# d
# names(d) <- c('College Major', 'Proffesional Career')
# head(d)

# First Sankey diagram
plot <- hchart(data_to_sankey(div1_ind), "sankey", name = "Proffesional Career according to College Major")

plot %>%
hc_title(text= "College Major vs. Professional Career Industry") %>%
hc_subtitle(text= "Where do NCF students work after graduating?")  %>%
hc_caption(text = "<b>Data from New College of Florida<b>")%>%
hc_add_theme(hc_theme_economist())
```
