---
title: "Untitled"
author: "Mei Maddox"
date: "2/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```


```{r include=FALSE}
df <- readr::read_csv("./NCAlumn - Industries Filled")

df.subset <- df %>%
  filter_at(vars(matches("3")), all_vars(is.na(.))) %>%
  select(matches("DIVISION|ACADEMIC_PROGRAM"),Industry,-matches("3")) %>%
  mutate(Industry_Category=forcats::fct_collapse(Industry,
                                      `Arts and Media`=c("Art","Arts","Antiques","Arts & Entertainment","Online Media","Performing Arts","Communications","Entertainment","Film","Journalism","Media","Music","Photography","Publishing"),
                                      `Health and Medicine`=c("Dentistry","Health & Fitness","Healthcare","Healthcare Services","Medical","Medical Equipment","Medical Research","Medicine","Pharmaceutical","Psychotherapy","Public Health"),
                                      `Government and Social Services`=c("Attorney","City/County/State","Community Services","Defense & Space","Development","Economic Development","Environmental Law","Government","International Relations","Law","Military","Non Profit","Nonprofit","Philanthropy","Public Relations","Religion"),
                                      `Education`=c("Education","Education / Training","Educational Services","Higher education","Library","Museums and Institutions"),
                                      `STEM`=c('Agriculture','Archaeology','Architecture','Computer Software','Construction','Data Science','Electronics','Engineering','Environmental','Environmental Science','Environmental Services','Farming','Imaging','Information Technology','IT Communications','Manufacturing','Marine','Research','Software','Software Design','Technology','Textiles'),
                                      `Business, Finance, and Retail`=c('Accounting','Advertising','Banking','Business','Business Consulting','Consulting','Financial Services','Food','Food and Lodging','Food Franchise','Food Service','Health Care Consulting','Home Improvement','Hospitality','Human Resources','Insurance','International Economic Development Consulting','Investment banking','Investments','Marketing','Non-profit consulting','Pet Food','Real Estate','Restaurant','Retail','Services','Shipping','Sports Management','Transportation'))) %>%
  mutate(Industry_Category=forcats::fct_other(Industry_Category, keep = c("Arts and Media","Business, Finance, and Retail","STEM","Education","Health and Medicine","Government and Social Services")))
```
